#!/usr/bin/env python3
"""rgb.txt (X11 color names, MIT license, from Debian x11-common) -> src/x11/colors-data.ts.
usage: gen-colors.py rgb.txt OUT.ts"""
import sys
src, out = sys.argv[1:]
seen = {}
for line in open(src, encoding='latin-1'):
    if line.startswith('!') or not line.strip(): continue
    p = line.split()
    r, g, b = int(p[0]), int(p[1]), int(p[2])
    name = ''.join(p[3:]).lower()
    seen.setdefault(name, (r << 16) | (g << 8) | b)
with open(out, 'w') as f:
    f.write('// Generated by scripts/gui/gen-colors.py from X11 rgb.txt. Do not edit.\n')
    f.write('// name (lowercase, no spaces) -> 0xRRGGBB, packed as "name:hex" pairs\n')
    f.write('export const RGB_TXT = ' + repr(' '.join('%s:%06x' % (k, v) for k, v in seen.items())).replace("'", '"') + ';\n')
