import { it, expect } from 'vitest';
import { createTestShell } from './helpers';
import { nodeCmd } from '@shiro/commands/jseval';
it('node fs keeps binary data byte-exact (FLAC, images)', async () => {
  const { shell, fs } = await createTestShell();
  const code = `const fs=require('fs');
const hex=(b)=>[...b].map(x=>x.toString(16)).join(' ');
const b=Buffer.from([0x66,0x4c,0x61,0x43,0xff,0xfe,0x00,0x80,0x81,0xc3]);
fs.writeFileSync('/tmp/a.flac', b);
console.log('sync', fs.statSync('/tmp/a.flac').size, hex(fs.readFileSync('/tmp/a.flac')), fs.existsSync('/tmp/a.flac'), fs.readdirSync('/tmp').includes('a.flac'));
fs.appendFileSync('/tmp/c.bin', Buffer.from([0xff,0x00])); fs.appendFileSync('/tmp/c.bin', Buffer.from([0x81]));
console.log('append', hex(fs.readFileSync('/tmp/c.bin')));
fs.writeFileSync('/tmp/t.tmp', b); fs.renameSync('/tmp/t.tmp', '/tmp/final.flac');
console.log('rename', hex(fs.readFileSync('/tmp/final.flac')), fs.existsSync('/tmp/t.tmp'));
fs.writeFileSync('/tmp/u.txt', 'héllo'); console.log('text', fs.statSync('/tmp/u.txt').size, fs.readFileSync('/tmp/u.txt','utf8'));
(async()=>{ await fs.promises.writeFile('/tmp/b.flac', b); console.log('prom', hex(await fs.promises.readFile('/tmp/b.flac')));
 const fd=fs.openSync('/tmp/d.bin','w'); fs.writeSync(fd, Buffer.from([0xfa,0x01])); fs.closeSync(fd); console.log('fd', hex(fs.readFileSync('/tmp/d.bin'))); })();`;
  const ctx: any = { args: ['-e', code], fs, cwd: '/', env: { ...shell.env }, stdin: '', stdout: '', stderr: '', shell };
  await nodeCmd.exec(ctx);
  const o = ctx.stdout.replace(/\r/g, '');
  await new Promise(r => setTimeout(r, 300));
  const F = '66 4c 61 43 ff fe 0 80 81 c3';
  expect(o).toContain(`sync 10 ${F} true true`);
  expect(o).toContain('append ff 0 81');
  expect(o).toContain(`rename ${F} false`);
  expect(o).toContain('text 6 héllo');
  expect(o).toContain(`prom ${F}`);
  expect(o).toContain('fd fa 1');
  const hex = (d: any) => [...d].map((x: number) => x.toString(16)).join(' ');
  expect(hex(await fs.readFile('/tmp/a.flac'))).toBe(F);
  expect(hex(await fs.readFile('/tmp/final.flac'))).toBe(F);
  expect(hex(await fs.readFile('/tmp/c.bin'))).toBe('ff 0 81');
});
