#!/usr/bin/env node
/**
 * Build docs/CONFORMANCE.md from the conformance results
 * (tests/conformance/results/*.json, written by `npm run conformance`).
 *
 * Each results file is { suite, title?, note?, files: { area: { pass, total, failures: [{ name, ... }] } } }.
 * tests/conformance/results/before/<same name>.json, when present, is the
 * score at the start of the conformance work and is shown alongside.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const RESULTS = join(ROOT, 'tests/conformance/results');
const ORDER = ['shell-oils.json', 'shell-oils-browser.json', 'utils-busybox.json', 'syscalls-blink.json', 'syscalls-wasi.json'];

const files = readdirSync(RESULTS).filter((f) => f.endsWith('.json') && !f.endsWith('.partial.json'))
  .sort((a, b) => (ORDER.indexOf(a) + 1 || 99) - (ORDER.indexOf(b) + 1 || 99) || a.localeCompare(b));

const pct = (p, t) => (t ? `${((100 * p) / t).toFixed(1)}%` : '—');
const sum = (o) => Object.values(o).reduce((a, v) => ({ pass: a.pass + v.pass, total: a.total + v.total }), { pass: 0, total: 0 });

let summary = '| Suite | Before | Now |\n|---|---|---|\n';
let body = '';
for (const f of files) {
  const r = JSON.parse(readFileSync(join(RESULTS, f), 'utf8'));
  const beforePath = join(RESULTS, 'before', f);
  const before = existsSync(beforePath) ? JSON.parse(readFileSync(beforePath, 'utf8')) : null;
  const now = sum(r.files);
  const was = before ? sum(before.files) : null;
  const title = r.title || r.suite;
  summary += `| [${title}](#${title.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-')}) | ${was ? `${was.pass}/${was.total} (${pct(was.pass, was.total)})` : '—'} | **${now.pass}/${now.total} (${pct(now.pass, now.total)})** |\n`;

  body += `\n## ${title}\n\n`;
  if (r.note) body += `${r.note}\n\n`;
  body += '| Area | Before | Now | Failing |\n|---|---|---|---|\n';
  for (const [area, v] of Object.entries(r.files)) {
    const b = before?.files?.[area];
    body += `| ${area} | ${b ? `${b.pass}/${b.total}` : '—'} | ${v.pass}/${v.total} | ${v.total - v.pass} |\n`;
  }
  const failing = Object.entries(r.files).filter(([, v]) => v.failures?.length);
  if (failing.length) {
    body += '\n<details><summary>Failing cases</summary>\n\n';
    for (const [area, v] of failing) {
      body += `- **${area}**: ${v.failures.map((x) => `${x.name.replace(/[|<>]/g, (c) => `\\${c}`)}${x.timeout ? ' (hang/timeout)' : ''}${x.reason ? ` — ${x.reason}` : ''}`).join('; ')}\n`;
    }
    body += '\n</details>\n';
  }
}

const md = `# Conformance scoreboard

Generated by \`npm run conformance\` (scripts/conformance/report.mjs); do not edit by hand.
"Before" is the score of the same suites on unix/integration before the
conformance work started (fc0af54).

${summary}
How each suite runs, and what is and isn't scored, is described in
[tests/conformance/README.md](../tests/conformance/README.md).
${body}`;
writeFileSync(join(ROOT, 'docs/CONFORMANCE.md'), md);
console.log('wrote docs/CONFORMANCE.md');
