// Regenerates docs/BENCHMARKS.md from a results file. The "Hotspots" and
// "Notes" sections are hand-written: everything between the
// <!-- bench:table --> markers is replaced, the rest is kept.
//   node bench/report.mjs bench/results/<file>.json
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BEGIN = '<!-- bench:table:begin -->';
const END = '<!-- bench:table:end -->';

const fmt = (x) => (x == null ? '—' : String(x));
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');

export function renderTable(data, sourceName) {
  const { env, results } = data;
  const lines = [];
  lines.push(`Generated by \`npm run bench\` from \`${sourceName}\` on ${env.date.slice(0, 10)} at ${env.git.short} (${env.git.branch}${env.git.dirty ? ', dirty' : ''}).`);
  lines.push(`Environment: ${env.cpu.count}× ${env.cpu.model}, ${env.memoryGiB} GiB, ${env.os}, Node ${env.node}, Chromium ${env.chromium} headless. ${env.runs} runs per metric unless *n* says otherwise; ${env.quick ? 'quick mode' : 'full mode'}, ${env.durationSec} s total.`);
  lines.push('');
  const modes = [...new Set(results.map((r) => r.mode))];
  for (const mode of modes) {
    const rows = results.filter((r) => r.mode === mode);
    lines.push(`### ${mode === 'isolated' ? 'Cross-origin isolated (SharedArrayBuffer, Blink, Worker processes)' : 'Not isolated (fallbacks: JSPI / in-page runtimes, src/x86)'}`);
    lines.push('');
    let group = null;
    for (const r of rows) {
      const g = r.name.split('.')[0];
      if (g !== group) {
        if (group !== null) lines.push('');
        group = g;
        lines.push(`| ${g} metric | median | p90 | unit | n | notes |`);
        lines.push('|---|---:|---:|---|---:|---|');
      }
      lines.push(`| \`${r.name}\` | ${fmt(r.median)} | ${fmt(r.p90)} | ${r.unit} | ${r.n} | ${esc(r.notes)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export function writeReport(data, docPath, sourceName) {
  const table = `${BEGIN}\n${renderTable(data, sourceName)}\n${END}`;
  let doc = existsSync(docPath) ? readFileSync(docPath, 'utf8') : `# Benchmarks\n\n${BEGIN}\n${END}\n`;
  if (!doc.includes(BEGIN)) doc += `\n## Results\n\n${BEGIN}\n${END}\n`;
  doc = doc.slice(0, doc.indexOf(BEGIN)) + table + doc.slice(doc.indexOf(END) + END.length);
  writeFileSync(docPath, doc);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const file = process.argv[2];
  if (!file) { console.error('usage: node bench/report.mjs <results.json> [docs/BENCHMARKS.md]'); process.exit(2); }
  const doc = process.argv[3] || join(ROOT, 'docs/BENCHMARKS.md');
  writeReport(JSON.parse(readFileSync(file, 'utf8')), doc, relative(ROOT, file));
  console.log(`wrote ${relative(ROOT, doc)}`);
}
