#!/bin/sh
# Build agentprobe (a static, freestanding x86-64 Linux binary) and embed it
# in src/commands/agent-probe-bin.ts for `doctor --agents`.
set -e
here=$(cd "$(dirname "$0")" && pwd)
out=$(mktemp -d)
gcc -static -nostdlib -fno-stack-protector -fno-builtin -fno-pie -no-pie -Os -s \
  -o "$out/agentprobe" "$here/agentprobe.c"
b64=$(base64 -w0 "$out/agentprobe")
cat > "$here/../../src/commands/agent-probe-bin.ts" <<TS
// Generated by scripts/agent-probe/build.sh from scripts/agent-probe/agentprobe.c: do not edit.
// A static x86-64 Linux binary ($(wc -c < "$out/agentprobe") bytes) that \`doctor --agents\` runs under Blink.
export const AGENT_PROBE_BASE64 = '$b64';
TS
rm -rf "$out"
echo "wrote src/commands/agent-probe-bin.ts"
