/**
 * Core X fonts for the in-page X server: the misc-fixed bitmap fonts from
 * xfonts-base (fonts-data.ts, generated by scripts/gui/gen-fonts.py), their
 * XLFD names and aliases, and pattern matching for OpenFont/ListFonts.
 */
import { FONTS, ALIASES, type RawFont } from './fonts-data';

export interface Glyph {
  lsb: number; rsb: number; width: number; ascent: number; descent: number;
  /** rows of ceil((rsb - lsb) / 8) bytes, MSB first; height = ascent + descent */
  bits: Uint8Array;
}

export interface CharInfo { lsb: number; rsb: number; width: number; ascent: number; descent: number; attr: number }

export interface XFont {
  name: string;
  ascent: number;
  descent: number;
  minByte1: number; maxByte1: number;
  minChar2: number; maxChar2: number;
  defaultChar: number;
  allExist: boolean;
  minBounds: CharInfo;
  maxBounds: CharInfo;
  props: [string, number | string][];
  glyph(code: number): Glyph | undefined;
  /** 16-bit codes in range order, for QueryFont's char infos */
  infoAt(code: number): CharInfo;
}

interface Face { raw: RawFont; glyphs: Map<number, Glyph>; unicode: boolean }

let faces: Face[] | null = null;

function loadFaces(): Face[] {
  if (faces) return faces;
  faces = FONTS.map((raw) => {
    const bin = atob(raw.bits);
    const bits = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bits[i] = bin.charCodeAt(i);
    const glyphs = new Map<number, Glyph>();
    let maxCode = 0;
    for (const [code, lsb, rsb, width, ascent, descent, off] of raw.glyphs) {
      const len = Math.ceil((rsb - lsb) / 8) * (ascent + descent);
      glyphs.set(code, { lsb, rsb, width, ascent, descent, bits: bits.subarray(off, off + len) });
      if (code > maxCode) maxCode = code;
    }
    return { raw, glyphs, unicode: maxCode > 0xff };
  });
  return faces;
}

/** XLFD with its registry/encoding replaced. */
function withCharset(xlfd: string, charset: string): string {
  const parts = xlfd.split('-');
  parts.splice(parts.length - 2, 2, ...charset.split('-'));
  return parts.join('-');
}

let names: { name: string; face: Face; charset: 'iso8859-1' | 'iso10646-1' }[] | null = null;

/** Every font name the server lists (lowercase XLFDs plus aliases). */
export function fontNames() {
  if (names) return names;
  names = [];
  for (const face of loadFaces()) {
    const x = face.raw.xlfd.toLowerCase();
    names.push({ name: withCharset(x, 'iso8859-1'), face, charset: 'iso8859-1' });
    if (face.unicode) names.push({ name: withCharset(x, 'iso10646-1'), face, charset: 'iso10646-1' });
  }
  return names;
}

function globToRegExp(pat: string): RegExp {
  let re = '^';
  for (const ch of pat.toLowerCase()) {
    if (ch === '*') re += '.*';
    else if (ch === '?') re += '.';
    else re += ch.replace(/[\\^$.|+()[\]{}]/g, '\\$&');
  }
  return new RegExp(re + '$');
}

/** ListFonts: names matching a pattern (XLFDs and aliases). */
export function listFonts(pattern: string, max: number): string[] {
  const re = globToRegExp(pattern);
  const out: string[] = [];
  for (const [alias] of ALIASES) if (re.test(alias.toLowerCase()) && resolveName(alias)) out.push(alias);
  for (const n of fontNames()) if (re.test(n.name)) out.push(n.name);
  return [...new Set(out)].slice(0, max);
}

function resolveName(name: string): { face: Face; charset: string; name: string } | null {
  let lower = name.toLowerCase();
  // The cursor font (XCreateFontCursor): glyph cursors become CSS cursors, so any face will do
  if (lower === 'cursor' || lower === 'decw$cursor') lower = 'fixed';
  const alias = ALIASES.find(([a]) => a.toLowerCase() === lower);
  const target = alias ? alias[1].toLowerCase() : lower;
  const re = globToRegExp(target);
  const hit = fontNames().find((n) => re.test(n.name));
  return hit ? { face: hit.face, charset: hit.charset, name: hit.name } : null;
}

/**
 * Lenient fallback for names no face matches (helvetica, times, lucida...):
 * the fixed face closest to the requested pixel size, so the app draws text
 * instead of failing to start.
 */
function fallbackFor(name: string): { face: Face; charset: string; name: string } | null {
  const lower = name.toLowerCase();
  if (!lower.startsWith('-')) return null;
  const f = lower.split('-');
  const px = parseInt(f[7], 10) || Math.round((parseInt(f[8], 10) || 120) / 10 * 1.1) || 13;
  const bold = f[3] === 'bold' || f[3] === 'demibold';
  const charset = f.length >= 15 && f[13] === 'iso10646' ? 'iso10646-1' : 'iso8859-1';
  let best: Face | null = null;
  let bestScore = Infinity;
  for (const face of loadFaces()) {
    if (charset === 'iso10646-1' && !face.unicode) continue;
    const x = face.raw.xlfd.toLowerCase().split('-');
    const h = parseInt(x[7], 10);
    const score = Math.abs(h - px) * 4 + ((x[3] === 'bold') !== bold ? 1 : 0) + (x[4] !== 'r' ? 3 : 0);
    if (score < bestScore) { bestScore = score; best = face; }
  }
  return best ? { face: best, charset, name: withCharset(best.raw.xlfd.toLowerCase(), charset) } : null;
}

const cache = new Map<string, XFont>();

export function openFont(name: string, lenient = true): XFont | null {
  const r = resolveName(name) ?? (lenient ? fallbackFor(name) : null);
  if (!r) return null;
  const key = r.name;
  const hit = cache.get(key);
  if (hit) return hit;
  const font = makeFont(r.face, r.charset === 'iso10646-1', r.name);
  cache.set(key, font);
  return font;
}

const ZERO: CharInfo = { lsb: 0, rsb: 0, width: 0, ascent: 0, descent: 0, attr: 0 };

function makeFont(face: Face, unicode: boolean, name: string): XFont {
  const raw = face.raw;
  let codes = [...face.glyphs.keys()];
  if (!unicode) codes = codes.filter((c) => c <= 0xff);
  const minByte1 = unicode ? Math.min(...codes.map((c) => c >> 8)) : 0;
  const maxByte1 = unicode ? Math.max(...codes.map((c) => c >> 8)) : 0;
  const minChar2 = unicode ? 0 : Math.min(...codes);
  const maxChar2 = unicode ? 0xff : Math.max(...codes);
  const minB = { lsb: Infinity, rsb: Infinity, width: Infinity, ascent: Infinity, descent: Infinity, attr: 0 };
  const maxB = { lsb: -Infinity, rsb: -Infinity, width: -Infinity, ascent: -Infinity, descent: -Infinity, attr: 0 };
  for (const c of codes) {
    const g = face.glyphs.get(c)!;
    for (const k of ['lsb', 'rsb', 'width', 'ascent', 'descent'] as const) {
      minB[k] = Math.min(minB[k], g[k]);
      maxB[k] = Math.max(maxB[k], g[k]);
    }
  }
  const glyph = (code: number) => (unicode || code <= 0xff ? face.glyphs.get(code) : undefined);
  const props: [string, number | string][] = [];
  for (const [k, v] of Object.entries(raw.props)) {
    if (k === 'CHARSET_REGISTRY') props.push([k, unicode ? 'ISO10646' : 'ISO8859']);
    else if (k === 'CHARSET_ENCODING') props.push([k, '1']);
    else props.push([k, v]);
  }
  props.push(['FONT', name.toUpperCase()]);
  const span = (maxByte1 - minByte1 + 1) * (maxChar2 - minChar2 + 1);
  return {
    name,
    ascent: raw.ascent,
    descent: raw.descent,
    minByte1, maxByte1, minChar2, maxChar2,
    defaultChar: raw.default,
    allExist: codes.length === span,
    minBounds: minB,
    maxBounds: maxB,
    props,
    glyph,
    infoAt(code: number): CharInfo {
      const g = glyph(code);
      return g ? { lsb: g.lsb, rsb: g.rsb, width: g.width, ascent: g.ascent, descent: g.descent, attr: 0 } : ZERO;
    },
  };
}

/** Text extents of 16-bit codes (missing glyphs use the default char). */
export function textExtents(font: XFont, codes: ArrayLike<number>) {
  let width = 0, left = 0, right = 0, ascent = 0, descent = 0;
  for (let i = 0; i < codes.length; i++) {
    const g = font.glyph(codes[i]) ?? font.glyph(font.defaultChar);
    if (!g) continue;
    if (i === 0) left = g.lsb;
    left = Math.min(left, width + g.lsb);
    right = Math.max(right, width + g.rsb);
    ascent = Math.max(ascent, g.ascent);
    descent = Math.max(descent, g.descent);
    width += g.width;
  }
  return { width, left, right, ascent, descent };
}
